### ISSUE TITLE
Infografia_Arturo Angon Jose 

### ISSUE THREAD

**Issue by ArturoAngonJose** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-ArturoAngonJose#1]
[Infografía_Arturo Angón José.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-ArturoAngonJose/files/10837822/Infografia_Arturo.Angon.Jose.pdf)

**Comment by Rmz-Rigo** [comment]
CALIFICACION: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
